import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/UI/Navbar";
import SplashCursor from "@/components/SplashCursor";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "M Ahmad Mujtaba | Full Stack Developer",
  description: "Generated by M Ahmad Mujtaba",
};

export default function HomePageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${nunito.variable} antialiased relative`}
      >
        <div className="absolute z-9999 left-0 right-0 top-5">
          <Navbar />
        </div>

        {children}
      </body>
    </html>
  );
}
