import type { Metadata } from "next";
import { Nunito, Stack_Sans_Notch } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import GameHub from "@/components/game/GameHub";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});
const ssn = Stack_Sans_Notch({
  variable: "--font-stack-sans-notch",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "M Ahmad Mujtaba | Full Stack Developer",
  description: "Generated by M Ahmad Mujtaba",
};

export default function HomePageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${ssn.variable} antialiased relative`}
      >
        <div className="absolute z-9998 left-0 right-0 top-5">
          <Navbar />
        </div>

        {children}

        <Footer />

        <GameHub />
      </body>
    </html>
  );
}
